name: My first workflow

on: push

jobs:
    ascii-job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install cowsay program
              run: sudo apt-get install -y cowsay

            - name: Excute cowsay CMD
              run: cowsay -f dragon "run for cover, Im a dragon" >> dragon.txt

            - name: Test if the file exists
              run: grep -i "dragon" dragon.txt

            - name: read file
              run: cat dragon.txt

            - name: list the repo files
              run: ls -ltra

            # - name: List and read files
            #   run: |
            #       echo "My first github action"
            #       ls -ltra
            #       cat README.md

            # - name: generate ASCII artwork
            #   run: cowsay -f dragon "run for cover, Im a dragon" >> dragon.txt

            # - name: List files
            #   run: ls -la

            # - name: Read file
            #   run: cat README.md
